# Le mot de passe pour le petit bloc "Clé d'accès" admin
password = "1234"

# Les accès pour le formulaire de connexion principal
[credentials]
UT = { pw = "Azerty123*", role = "Utilisateur" }
ANIM = { pw = "Anim2026*", role = "Animateur" }
